(()=>{
const css=`
/* Dedicated pre-draft lobby. The draft room does not exist visually until START DRAFT. */
body:not(.rd-live){overflow:auto!important;background:radial-gradient(circle at 72% 18%,#18324a 0,#091722 35%,#040b12 78%)!important;min-width:0!important}
body:not(.rd-live) .wrap{min-height:100vh!important;display:grid!important;place-items:center!important;padding:34px!important}
body:not(.rd-live) #room,body:not(.rd-live) #finish{display:none!important}
body:not(.rd-live) #setup{display:block!important;width:min(1040px,94vw)!important;max-width:none!important;margin:0!important;padding:0!important;border:1px solid #355269!important;border-radius:12px!important;overflow:hidden!important;background:linear-gradient(145deg,#0d1d2a,#08141f 70%)!important;box-shadow:0 28px 80px #000a!important;color:#fff!important}
#setup .rdLobbyTop{padding:34px 42px 28px;border-bottom:1px solid #294256;background:radial-gradient(circle at 80% 10%,#173a50 0,transparent 42%),linear-gradient(135deg,#0c1a26,#07121c)}
.rdBrand{font:italic 900 52px/.9 'Barlow Condensed',sans-serif;letter-spacing:-1px}.rdBrand span{color:#55e696}.rdTag{margin-top:9px;font:800 11px Inter,sans-serif;letter-spacing:2.6px;color:#8fa4b5}.rdChoose{margin-top:28px;font:italic 900 24px 'Barlow Condensed',sans-serif}.rdModes{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:13px}.rdMode{position:relative;padding:17px 17px 15px;border:1px solid #304b60;border-radius:7px;background:#0b1925;color:#dbe7ef;cursor:pointer}.rdMode b{display:block;font:italic 900 18px 'Barlow Condensed';color:#fff}.rdMode span{display:block;margin-top:5px;font:600 10px/1.4 Inter;color:#8197a8}.rdMode.active{border-color:#56e996;background:linear-gradient(145deg,#123426,#0b201b);box-shadow:inset 0 0 22px #4de28b18,0 0 16px #4de28b12}.rdMode.active:after{content:'SELECTED';position:absolute;right:10px;top:10px;font:800 8px Inter;color:#66f0a3;letter-spacing:1px}
#setup>.controls{display:grid!important;grid-template-columns:repeat(4,1fr)!important;gap:12px!important;padding:27px 42px 14px!important}.rdField{display:flex;flex-direction:column;gap:7px}.rdField label{font:italic 900 12px 'Barlow Condensed';color:#91a5b5;letter-spacing:.7px}.rdField select{width:100%;height:46px;padding:0 12px!important;border:1px solid #355168!important;border-radius:5px!important;background:#091723!important;color:#fff!important;font:800 12px Inter!important}.rdYear{height:46px;display:flex;align-items:center;padding:0 13px;border:1px solid #355168;border-radius:5px;background:#091723;font:800 12px Inter}.rdYear strong{color:#5ce99a;margin-left:auto}
#rosterConfig{margin:10px 42px 0!important;padding:17px!important;border:1px solid #2e485d!important;border-radius:7px!important;background:#091722!important;color:#fff!important;font-size:10px!important}#rosterConfig>b{font:italic 900 14px 'Barlow Condensed';color:#dce8ef}#rosterFields{gap:12px!important;margin-top:12px!important}#rosterFields label{color:#8198aa!important;font:800 9px Inter!important}#rosterFields input{width:44px!important;height:34px!important;background:#0d2030!important;color:#fff!important;border:1px solid #355269!important;border-radius:4px!important;text-align:center}#roundCount{color:#71899b!important}
.rdLaunch{padding:22px 42px 36px;display:flex;justify-content:flex-end;align-items:center;gap:18px}.rdLaunchNote{font:600 10px Inter;color:#71899b}.rdLaunch #start{min-width:180px;height:48px;border:0!important;border-radius:5px!important;background:linear-gradient(#f5c33b,#e9a71e)!important;color:#101820!important;font:italic 900 17px 'Barlow Condensed'!important;box-shadow:0 6px 18px #0006!important}.rdLaunch #start:hover{filter:brightness(1.08);transform:translateY(-1px)}
body.rd-live .setup{display:none!important}body.rd-live .wrap{display:block!important;padding:0!important}body.rd-live .room{display:grid!important}
/* no fake countdown: center status shows pick number instead */
body.rd-live .clock{font-size:29px!important;letter-spacing:.5px!important;color:#eaf3f8!important;text-shadow:none!important}
@media(max-width:850px){body:not(.rd-live) .wrap{padding:12px!important}.rdModes{grid-template-columns:1fr}.rdLobbyTop{padding:25px!important}#setup>.controls{grid-template-columns:1fr 1fr!important;padding:22px 25px 10px!important}#rosterConfig{margin:10px 25px 0!important}.rdLaunch{padding:20px 25px 28px}.rdBrand{font-size:44px}}
`;
let st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
function lobby(){const setup=document.getElementById('setup');if(!setup||setup.dataset.lobby)return;setup.dataset.lobby='1';
 const oldTitle=[...setup.children].filter(x=>x.tagName==='B'||x.tagName==='P');oldTitle.forEach(x=>x.remove());
 const top=document.createElement('div');top.className='rdLobbyTop';top.innerHTML=`<div class="rdBrand">RE:<span>DRAFT</span></div><div class="rdTag">FANTASY FOOTBALL TIME MACHINE</div><div class="rdChoose">CHOOSE YOUR GAME MODE</div><div class="rdModes"><div class="rdMode active" data-mode="classic"><b>TIME MACHINE DRAFT</b><span>Draft using only what managers knew before the season.</span></div><div class="rdMode" data-mode="challenge"><b>CHALLENGE MODE</b><span>Build the strongest roster you can from a historical draft room.</span></div><div class="rdMode" data-mode="custom"><b>CUSTOM DRAFT</b><span>Control league size, scoring, roster construction, and draft slot.</span></div></div>`;setup.prepend(top);
 const controls=setup.querySelector('.controls');if(controls){let selects=[...controls.querySelectorAll('select')];let labels=['TEAMS','DRAFT POSITION','SCORING'];selects.forEach((sel,i)=>{let w=document.createElement('div');w.className='rdField';sel.parentNode.insertBefore(w,sel);w.innerHTML=`<label>${labels[i]}</label>`;w.appendChild(sel)});let y=document.createElement('div');y.className='rdField';y.innerHTML='<label>SEASON</label><div class="rdYear">NFL SEASON <strong>2017</strong></div>';controls.prepend(y);}
 const start=document.getElementById('start');if(start){let launch=document.createElement('div');launch.className='rdLaunch';launch.innerHTML='<span class="rdLaunchNote">No hindsight. Historical draft-day player values.</span>';start.parentNode.removeChild(start);launch.appendChild(start);setup.appendChild(launch)}
 top.addEventListener('click',e=>{let m=e.target.closest('.rdMode');if(!m)return;top.querySelectorAll('.rdMode').forEach(x=>x.classList.toggle('active',x===m));window.REDRAFT_MODE=m.dataset.mode});
}
function patchStart(){if(typeof window.start!=='function')return setTimeout(patchStart,30);if(window.start.__lobby)return;const original=window.start;window.start=function(){document.body.classList.add('rd-live');original();setTimeout(()=>window.scrollTo(0,0),0)};window.start.__lobby=true;const b=document.getElementById('start');if(b)b.onclick=window.start}
function removeTimer(){let c=document.getElementById('clock');if(!c)return;let txt=document.getElementById('pickText')?.textContent||'YOUR PICK';c.textContent=txt.toUpperCase()}
new MutationObserver(()=>{if(document.body.classList.contains('rd-live'))removeTimer()}).observe(document.body,{subtree:true,childList:true,characterData:true});
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',()=>{lobby();patchStart()}):(lobby(),patchStart());
})();