(()=>{const css=`
/* RE:DRAFT polish v2 */
body{background:#050d15!important}.setup{position:relative!important;max-width:1120px!important;min-height:620px!important;margin:0 auto!important;padding:0!important;border:1px solid #304c61!important;border-radius:12px!important;overflow:hidden!important;background:radial-gradient(circle at 72% 35%,#203b4d 0,#0d1d2b 28%,#07131e 64%,#050c13 100%)!important;box-shadow:0 30px 90px #000b!important}.setup:before{content:'RE:DRAFT';display:block;padding:55px 64px 0;color:#f6f8fa;font:italic 900 72px/.85 'Barlow Condensed',sans-serif;letter-spacing:-3px;text-shadow:4px 5px #000}.setup:after{content:'BUILD YOUR 2017 TEAM.  NO HINDSIGHT.';position:absolute;left:68px;top:125px;color:#61eda0;font:800 12px Inter,sans-serif;letter-spacing:2.2px}.setup>b{display:block!important;margin:105px 68px 8px!important;font:italic 900 35px 'Barlow Condensed',sans-serif!important;text-transform:uppercase}.setup>p{margin:0 68px 28px!important;max-width:510px;color:#91a6b6!important;font-size:12px!important;line-height:1.6}.setup .controls{margin:0 68px!important;padding:22px!important;max-width:720px;background:#091824cc!important;border:1px solid #2c4659!important;border-radius:8px!important;box-shadow:inset 0 0 24px #0004!important}.setup select{height:43px!important;min-width:125px!important;background:#0c1d2b!important;color:#fff!important;border:1px solid #3b586c!important;border-radius:5px!important;font-weight:800!important}.setup #start{height:43px!important;padding:0 26px!important;border:0!important;border-radius:5px!important;background:linear-gradient(180deg,#ffd04c,#e9a61b)!important;color:#07111a!important;font:italic 900 16px 'Barlow Condensed',sans-serif!important;box-shadow:0 6px 20px #e7a51b2e!important}.setup #start:hover{transform:translateY(-1px);filter:brightness(1.08)}.setup [class*=roster],.setup #rosterSettings{background:#0a1824!important;color:#dbe6ee!important;border-color:#2a4355!important}.setup input{background:#0d2030!important;color:#fff!important;border:1px solid #3a5669!important}
/* never allow legacy white enhancement surfaces into the room */
.focus-card,.draft-tools{display:none!important}.players{background:#07131e!important;color:#edf5fb!important}.player{color:#dce8ef!important}.player *{color:inherit}.player .nm{color:#fff!important}.player .meta{color:#7f96a8!important}.player .draft{color:#6ff0a7!important}.playerTableHead{background:#081722!important}.filters{background:#091824!important}.teamRail,.side,main{background:#07141f!important}.finish{background:#081722!important;color:#edf5fb!important;border-color:#314b60!important}
@media(max-width:1200px){.setup{max-width:94vw!important;min-height:570px!important}.setup:before{padding-left:45px;font-size:62px}.setup:after{left:49px}.setup>b,.setup>p,.setup .controls{margin-left:49px!important;margin-right:49px!important}}
`;let s=document.createElement('style');s.textContent=css;document.head.appendChild(s);
// The setup is a true landing state; draft room stays hidden until Start.
function state(){let setup=document.getElementById('setup'),room=document.getElementById('room');if(!setup||!room)return;document.body.classList.toggle('landing-active',getComputedStyle(setup).display!=='none')}
new MutationObserver(state).observe(document.body,{subtree:true,attributes:true,attributeFilter:['style'],childList:true});state();
})();