// Loads any selected 2000-2026 historical market into the shared draft engine.
(()=>{
 const q=new URLSearchParams(location.search),initial=+(q.get('year')||2017);
 window.REDRAFT_SELECTED_YEAR=initial;window.REDRAFT_SEASON_READY=false;window.REDRAFT_SEASON_ERROR=null;window.REDRAFT_SEASON_CACHE=window.REDRAFT_SEASON_CACHE||{};
 const scoring=()=>{const raw=String(document.getElementById('scoring')?.value||'standard').toLowerCase();return raw.includes('ppr')&&!raw.includes('half')?'ppr':'standard'};
 function apply(y,j){if(!Array.isArray(j.players)||j.players.length<40)throw Error('insufficient player pool');P.splice(0,P.length,...j.players.map((x,i)=>({...x,id:i,season:y})));window.REDRAFT_REGISTER_SEASON?.(y,P,{source:j.source,status:'playable'});window.REDRAFT_SELECTED_YEAR=y;window.REDRAFT_SEASON_READY=true;window.REDRAFT_SEASON_ERROR=null;document.title=`RE:DRAFT — ${y}`;document.dispatchEvent(new CustomEvent('redraft-season-ready',{detail:{year:y,count:P.length,source:j.source}}));return j}
 window.REDRAFT_LOAD_SEASON=async function(y=window.REDRAFT_SELECTED_YEAR,opts={}){y=+y;if(y<2000||y>2026)throw Error('season out of range');window.REDRAFT_SELECTED_YEAR=y;window.REDRAFT_SEASON_READY=false;window.REDRAFT_SEASON_ERROR=null;document.dispatchEvent(new CustomEvent('redraft-season-loading',{detail:{year:y}}));const teams=opts.teams||document.getElementById('teams')?.value||12,fmt=opts.scoring||scoring(),key=`${y}-${teams}-${fmt}`;try{if(window.REDRAFT_SEASON_CACHE[key])return apply(y,window.REDRAFT_SEASON_CACHE[key]);const r=await fetch(`/api/season?year=${y}&teams=${encodeURIComponent(teams)}&scoring=${fmt}`);let j;try{j=await r.json()}catch{throw Error(`season service returned ${r.status}`)}if(!r.ok)throw Error(j.detail||j.error||'season load failed');window.REDRAFT_SEASON_CACHE[key]=j;return apply(y,j)}catch(err){window.REDRAFT_SEASON_ERROR=err;window.REDRAFT_SEASON_READY=false;document.dispatchEvent(new CustomEvent('redraft-season-error',{detail:{year:y,error:String(err.message||err)}}));throw err}};
 window.REDRAFT_SET_YEAR=async function(y){window.REDRAFT_SELECTED_YEAR=+y;history.replaceState(null,'',`${location.pathname}?year=${y}`);return window.REDRAFT_LOAD_SEASON(+y)};
 window.REDRAFT_SEASON_PROMISE=window.REDRAFT_LOAD_SEASON(initial).catch(()=>null);
})();