const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
let drafts=0,picksTested=0;const summary={earlyBackupQB:0,earlyBackupTE:0,earlyK:0,earlyDST:0,unrankedBeforeRanked:0,firstRounds:[]};
for(let year=2000;year<=2026;year++)for(const variant of ['default','two-qb','no-k-dst','no-qb'])for(let seed=1;seed<=3;seed++){
 const players=require(`../data/seasons/${year}.json`).players.map(p=>({...p,adp:p.pprAdp??p.standardAdp??p.adp})),n=variant==='no-k-dst'?10:seed%2?12:10;
 const cfg=variant==='no-qb'?{QB:0,RB:2,WR:3,TE:0,FLEX:0,K:0,DST:0,BENCH:6}:variant==='two-qb'?{QB:2,RB:2,WR:2,TE:1,FLEX:1,K:1,DST:1,BENCH:5}:variant==='no-k-dst'?{QB:1,RB:2,WR:3,TE:1,FLEX:2,K:0,DST:0,BENCH:6}:{QB:1,RB:2,WR:2,TE:1,FLEX:1,K:1,DST:1,BENCH:6};
 const total=Object.values(cfg).reduce((a,b)=>a+b,0),context={avail:players.map(p=>({...p})),rosters:Array.from({length:n},()=>[]),n,pick:0,window:{REDRAFT_ROSTER:cfg,REDRAFT_ROUNDS:total,}};
 context.document={readyState:'loading',addEventListener(){}};context.setTimeout=()=>{};vm.createContext(context);vm.runInContext(fs.readFileSync(require.resolve('../roster-settings.js'),'utf8'),context);context.window.REDRAFT_ROSTER=cfg;vm.runInContext(fs.readFileSync(require.resolve('../gameplay.js'),'utf8'),context);let state=seed*year;const rng=()=>((state=Math.imul(state,1664525)+1013904223>>>0)/4294967296);
 const drafted=new Set();for(let pick=0;pick<n*total;pick++){context.pick=pick;const r=Math.floor(pick/n),t=r%2?n-1-pick%n:pick%n,p=context.window.REDRAFT_CPU_CHOICE(t,rng);assert(p,`${year} ${variant} seed ${seed} pick ${pick} pool exhausted; roster ${JSON.stringify(context.rosters[t].map(p=>p.pos))}; available ${JSON.stringify(context.avail.map(p=>p.pos))}`);assert(!drafted.has(p.id));const round=Math.floor(pick/n)+1,roster=context.rosters[t];if(p.pos==='QB'&&cfg.QB===1&&roster.some(x=>x.pos==='QB')&&round<=9)summary.earlyBackupQB++;if(p.pos==='TE'&&roster.some(x=>x.pos==='TE')&&round<=7)summary.earlyBackupTE++;if(p.pos==='K'&&round<total-2)summary.earlyK++;if(p.pos==='DST'&&round<total-2)summary.earlyDST++;if(p.unranked&&['QB','RB','WR','TE'].includes(p.pos)&&context.avail.some(x=>!x.unranked&&x.adp<180&&['RB','WR'].includes(x.pos)))summary.unrankedBeforeRanked++;if(variant==='default'&&seed===1&&[2003,2010,2017,2024,2026].includes(year)&&pick<24)summary.firstRounds.push({year,pick:pick+1,name:p.name,pos:p.pos,adp:p.adp});drafted.add(p.id);context.rosters[t].push(p);context.avail=context.avail.filter(x=>x.id!==p.id);picksTested++}
 for(const roster of context.rosters){assert.equal(roster.length,total);const count=pos=>roster.filter(p=>p.pos===pos).length;for(const pos of ['QB','RB','WR','TE','K','DST'])assert(count(pos)>=cfg[pos],`${year} ${variant} missing ${pos}`);assert(['RB','WR','TE'].reduce((s,pos)=>s+Math.max(0,count(pos)-cfg[pos]),0)>=cfg.FLEX);assert.equal(count('K'),cfg.K,`${year} ${variant} K`);assert.equal(count('DST'),cfg.DST,`${year} ${variant} DST`);assert(count('QB')<=(cfg.QB?Math.max(cfg.QB,2):0));if(!cfg.TE&&!cfg.FLEX)assert.equal(count('TE'),0);}
 assert.equal(context.avail.length+drafted.size,players.length);assert.equal(new Set(players.filter(p=>p.pos==='DST').map(p=>p.team)).size,players.filter(p=>p.pos==='DST').length);drafts++;
}
console.log(JSON.stringify({passed:true,drafts,picksTested,seasons:27,configurations:4,seeds:3}));

for(const k of ['earlyBackupQB','earlyBackupTE','earlyK','earlyDST'])assert.equal(summary[k],0,k);fs.writeFileSync(require('path').join(__dirname,'cpu-quality-results.json'),JSON.stringify(summary,null,2)+'\n');console.log(JSON.stringify(summary,null,2));
