// Replay the actual downloaded/decoded CDN image bytes in Chromium. Network availability
// is audited separately by the downloader; this tests browser decoding and UI integration.
const {chromium}=require('playwright'),fs=require('fs'),assert=require('assert/strict'),http=require('http'),path=require('path'),vm=require('vm');
const root=path.resolve(__dirname,'..'),cache=JSON.parse(fs.readFileSync(process.env.PHOTO_CHECKS,'utf8')),c={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'verified-portraits.js'),'utf8'),c);const records=Object.values(c.window.REDRAFT_VERIFIED_PORTRAITS),byUrl=new Map(Object.values(cache).filter(v=>v.url).map(v=>[v.url,v]));
const handler=require('../api/season.js'),server=http.createServer(async(req,res)=>{const u=new URL(req.url,'http://local');if(u.pathname==='/api/season'){req.query=Object.fromEntries(u.searchParams);res.status=s=>(res.statusCode=s,res);res.json=j=>res.end(JSON.stringify(j));return handler(req,res)}const f=path.join(root,u.pathname);if(!f.startsWith(root)||!fs.existsSync(f)){res.writeHead(404).end();return}res.setHeader('content-type',f.endsWith('.js')?'application/javascript':'text/html');fs.createReadStream(f).pipe(res)});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1440,height:900}});await page.route('https://**/*',async route=>{const r=byUrl.get(route.request().url());if(r)await route.fulfill({body:fs.readFileSync(r.path),contentType:r.url.endsWith('.jpg')?'image/jpeg':'image/png'});else await route.abort()});
 const url=`http://127.0.0.1:${server.address().port}`;await page.goto(url+'/play.html?year=2024');await page.waitForFunction(()=>window.REDRAFT_SEASON_READY);
 let decoded=0;for(let i=0;i<records.length;i+=32){const outcomes=await page.evaluate(async urls=>Promise.all(urls.map(src=>new Promise(resolve=>{const img=new Image();img.onload=()=>resolve(img.naturalWidth>0);img.onerror=()=>resolve(false);img.src=src}))),records.slice(i,i+32).map(r=>r.url));assert(outcomes.every(Boolean),`image batch ${i}`);decoded+=outcomes.length}
 await page.locator('#slot').selectOption('11');await page.locator('#start').click();await page.waitForFunction(()=>teamAt(pick)===user);await page.waitForFunction(()=>document.querySelector('.heroPhoto img')?.naturalWidth>0);assert(await page.locator('#players img[loading="lazy"]').count()>100);await page.screenshot({path:path.join(root,'tests/qa-photos.png')});await page.locator('#boardTab').click();await page.screenshot({path:path.join(root,'tests/qa-board.png')});await page.locator('#playersTab').click();
 // A failed photo must resolve once to a deliberate graphic, without retries/render loops.
 await page.evaluate(()=>{document.querySelector('.heroPhoto img').src='/deliberate-missing-photo.png'});await page.waitForFunction(()=>!!document.querySelector('.heroPhoto .fallback svg'));assert.equal(await page.locator('.heroPhoto img').count(),0);
 await browser.close();await new Promise(r=>server.close(r));console.log(JSON.stringify({decoded,visibleHero:true,lazyPlayerImages:true,failedImageFallback:true}));})().catch(e=>{console.error(e);process.exit(1)});
