// RE:DRAFT historical season API — preseason draft-market data, no hindsight stats.
module.exports=async function handler(req,res){
 const year=Number(req.query.year),scoring=String(req.query.scoring||'standard').toLowerCase(),teams=Math.min(16,Math.max(8,Number(req.query.teams)||12));
 if(!Number.isInteger(year)||year<2000||year>2026)return res.status(400).json({error:'year must be 2000-2026'});
 const pos=x=>{x=String(x||'').toUpperCase().replace(/[^A-Z/]/g,'');if(x==='PK')return'K';if(['DEF','DF','D/ST','DST'].includes(x))return'DST';return x};
 const arr=x=>Array.isArray(x)?x:x?[x]:[];
 const clean=s=>String(s||'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&#39;|&apos;/gi,"'").replace(/&quot;/gi,'"').replace(/\s+/g,' ').trim();
 const finalize=(rows,source)=>{const ok=rows.filter(Boolean).map(p=>({...p,pos:pos(p.pos),adp:Number(p.adp)})).filter(p=>p.name&&['QB','RB','WR','TE','K','DST'].includes(p.pos)&&Number.isFinite(p.adp)&&p.adp>0).sort((a,b)=>a.adp-b.adp),seen=new Set(),out=[];for(const p of ok){const k=p.name.toLowerCase()+'|'+p.pos;if(seen.has(k))continue;seen.add(k);out.push(p)}const count={};out.forEach((p,i)=>{p.id=i;count[p.pos]=(count[p.pos]||0)+1;p.pr=count[p.pos]});return{year,source,players:out.slice(0,420)}};
 async function getText(url){const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 RE-DRAFT historical fantasy simulator','accept':'text/html,application/json'}});if(!r.ok)throw Error(`${new URL(url).hostname} ${r.status}`);return r.text()}
 async function getJson(url){const text=await getText(url);try{return JSON.parse(text)}catch{throw Error('historical endpoint did not return JSON')}}
 async function mfl(){const base=`https://api.myfantasyleague.com/${year}/export`,fmt=scoring==='ppr'?1:0;let aj,pj;const variants=[`${base}?TYPE=adp&PERIOD=ALL&FCOUNT=${teams}&IS_PPR=${fmt}&IS_KEEPER=N&IS_MOCK=-1&CUTOFF=1&JSON=1`,`${base}?TYPE=adp&PERIOD=ALL&FCOUNT=${teams}&IS_PPR=${fmt}&JSON=1`,`${base}?TYPE=adp&FCOUNT=${teams}&JSON=1`,`${base}?TYPE=adp&JSON=1`];let errs=[];for(const u of variants){try{aj=await getJson(u);if(arr(aj.adp?.player).length)break}catch(e){errs.push(e.message)}}if(!aj||!arr(aj.adp?.player).length)throw Error(`MFL ADP empty ${errs.join(',')}`);pj=await getJson(`${base}?TYPE=players&DETAILS=1&JSON=1`);const players=arr(pj.players?.player),byId=new Map(players.map(p=>[String(p.id),p]));let rows=arr(aj.adp?.player).map(a=>{const m=byId.get(String(a.id));if(!m)return null;let name=m.name||m.fullName||[m.firstName,m.lastName].filter(Boolean).join(' ');if(name.includes(', ')){let [last,...rest]=name.split(', ');name=rest.join(', ')+' '+last}return{name,pos:m.position,team:m.team||m.nfl_team||'FA',adp:a.averagePick||a.averagepick||a.adp||a.avgPick,mflId:String(a.id),espnId:m.espn_id||m.espnId||m.espnid||null}});return finalize(rows,'MyFantasyLeague historical ADP')}
 async function ffc(){if(year<2007)throw Error('FFC historical API begins in 2007');const fmt=scoring==='ppr'?'ppr':'standard',j=await getJson(`https://fantasyfootballcalculator.com/api/v1/adp/${fmt}?teams=${teams}&year=${year}`),rows=arr(j.players||j.adp).map(x=>({name:x.name||x.player_name||x.playerName,pos:x.position||x.pos,team:x.team||x.team_abbr||'FA',adp:x.adp||x.average_pick||x.averagePick,ffcId:x.id||null}));return finalize(rows,'Fantasy Football Calculator historical ADP')}
 async function fftoday(){if(year!==2006&&year!==2007)throw Error('FF Today legacy ADP fallback covers 2006-2007');let html=await getText(year===2006?'https://www.fftoday.com/compiler/update/ADP.htm':'https://www.fftoday.com/rankings/07_adp.htm'),rows=[];for(const m of html.matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/gi)){const c=[...m[1].matchAll(/<td[^>]*>([\s\S]*?)<\/td>/gi)].map(x=>clean(x[1]));if(year===2006&&c.length>=21){let off=teams<=10?0:teams>=14?14:7,g=c.slice(off,off+7),rp=g[4],mm=String(rp).match(/(\d+)\.(\d+)/);if(mm)rows.push({name:g[2],pos:g[1],team:g[3],adp:(+mm[1]-1)*(teams<=10?10:teams>=14?14:12)+(+mm[2])})}else if(year===2007&&c.length>=5){let overall=Number(c[c.length-1]);if(Number.isFinite(overall))rows.push({name:c[1],pos:c[2],team:c[3],adp:overall})}}return finalize(rows,`FF Today ${year} archived preseason ADP`)}
 let data,errors=[],minimum=Math.max(120,teams*15);for(const fn of [mfl,ffc,fftoday]){try{const d=await fn();if(d.players.length>=minimum){data=d;break}errors.push(`${d.source}: only ${d.players.length}`)}catch(e){errors.push(String(e.message||e))}}
 if(!data)return res.status(502).json({error:'Historical season data unavailable',year,detail:errors.join(' | ')});
 res.setHeader('Cache-Control','public, s-maxage=86400, stale-while-revalidate=604800');res.setHeader('Access-Control-Allow-Origin','*');return res.status(200).json({...data,teams,scoring});
};