// RE:DRAFT historical season API — preseason market data with a resilient legacy-era fallback.
module.exports=async function handler(req,res){
 const year=Number(req.query.year),scoring=String(req.query.scoring||'standard').toLowerCase(),teams=Math.min(16,Math.max(8,Number(req.query.teams)||12));
 if(!Number.isInteger(year)||year<2000||year>2026)return res.status(400).json({error:'year must be 2000-2026'});
 const pos=x=>{x=String(x||'').toUpperCase().replace(/[^A-Z/]/g,'');if(x==='PK')return'K';if(['DEF','DF','D/ST','DST'].includes(x))return'DST';if(x==='FB')return'RB';return x};
 const arr=x=>Array.isArray(x)?x:x?[x]:[];
 const clean=s=>String(s||'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&#39;|&apos;/gi,"'").replace(/&quot;/gi,'"').replace(/\s+/g,' ').trim();
 const finalize=(rows,source)=>{const ok=rows.filter(Boolean).map(p=>({...p,pos:pos(p.pos),adp:Number(p.adp)})).filter(p=>p.name&&['QB','RB','WR','TE','K','DST'].includes(p.pos)&&Number.isFinite(p.adp)&&p.adp>0).sort((a,b)=>a.adp-b.adp),seen=new Set(),out=[];for(const p of ok){const k=p.name.toLowerCase()+'|'+p.pos;if(seen.has(k))continue;seen.add(k);out.push(p)}const count={};out.forEach((p,i)=>{p.id=i;count[p.pos]=(count[p.pos]||0)+1;p.pr=count[p.pos]});return{year,source,players:out.slice(0,420)}};
 async function getText(url){const c=new AbortController(),timer=setTimeout(()=>c.abort(),8000);try{const r=await fetch(url,{signal:c.signal,headers:{'user-agent':'Mozilla/5.0 RE-DRAFT historical fantasy simulator','accept':'text/html,application/json,text/plain'}});if(!r.ok)throw Error(`${new URL(url).hostname} ${r.status}`);return await r.text()}finally{clearTimeout(timer)}}
 async function getJson(url){const text=await getText(url);try{return JSON.parse(text)}catch{throw Error('historical endpoint did not return JSON')}}
 async function mfl(){const base=`https://api.myfantasyleague.com/${year}/export`,fmt=scoring==='ppr'?1:0;let aj,pj;const variants=[`${base}?TYPE=adp&PERIOD=ALL&FCOUNT=${teams}&IS_PPR=${fmt}&IS_KEEPER=N&IS_MOCK=-1&CUTOFF=1&JSON=1`,`${base}?TYPE=adp&PERIOD=ALL&FCOUNT=${teams}&IS_PPR=${fmt}&JSON=1`,`${base}?TYPE=adp&FCOUNT=${teams}&JSON=1`,`${base}?TYPE=adp&JSON=1`];let errs=[];for(const u of variants){try{aj=await getJson(u);if(arr(aj.adp?.player).length)break}catch(e){errs.push(e.message)}}if(!aj||!arr(aj.adp?.player).length)throw Error(`MFL ADP empty ${errs.join(',')}`);pj=await getJson(`${base}?TYPE=players&DETAILS=1&JSON=1`);const players=arr(pj.players?.player),byId=new Map(players.map(p=>[String(p.id),p]));let rows=arr(aj.adp?.player).map(a=>{const m=byId.get(String(a.id));if(!m)return null;let name=m.name||m.fullName||[m.firstName,m.lastName].filter(Boolean).join(' ');if(name.includes(', ')){let [last,...rest]=name.split(', ');name=rest.join(', ')+' '+last}return{name,pos:m.position,team:m.team||m.nfl_team||'FA',adp:a.averagePick||a.averagepick||a.adp||a.avgPick,mflId:String(a.id),espnId:m.espn_id||m.espnId||m.espnid||null}});return finalize(rows,'MyFantasyLeague historical ADP')}
 async function ffc(){if(year<2007)throw Error('FFC historical API begins in 2007');const fmt=scoring==='ppr'?'ppr':'standard',j=await getJson(`https://fantasyfootballcalculator.com/api/v1/adp/${fmt}?teams=${teams}&year=${year}`),rows=arr(j.players||j.adp).map(x=>({name:x.name||x.player_name||x.playerName,pos:x.position||x.pos,team:x.team||x.team_abbr||'FA',adp:x.adp||x.average_pick||x.averagePick,ffcId:x.id||null}));return finalize(rows,'Fantasy Football Calculator historical ADP')}
 async function fftoday(){if(year!==2006&&year!==2007)throw Error('FF Today legacy ADP fallback covers 2006-2007');let html=await getText(year===2006?'https://www.fftoday.com/compiler/update/ADP.htm':'https://www.fftoday.com/rankings/07_adp.htm'),rows=[];for(const m of html.matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/gi)){const c=[...m[1].matchAll(/<td[^>]*>([\s\S]*?)<\/td>/gi)].map(x=>clean(x[1]));if(year===2006&&c.length>=21){let off=teams<=10?0:teams>=14?14:7,g=c.slice(off,off+7),rp=g[4],mm=String(rp).match(/(\d+)\.(\d+)/);if(mm)rows.push({name:g[2],pos:g[1],team:g[3],adp:(+mm[1]-1)*(teams<=10?10:teams>=14?14:12)+(+mm[2])})}else if(year===2007&&c.length>=5){let overall=Number(c[c.length-1]);if(Number.isFinite(overall))rows.push({name:c[1],pos:c[2],team:c[3],adp:overall})}}return finalize(rows,`FF Today ${year} archived preseason ADP`)}
 function csvLine(line){let a=[],s='',q=false;for(let i=0;i<line.length;i++){let ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){s+='"';i++}else q=!q}else if(ch===','&&!q){a.push(s);s=''}else s+=ch}a.push(s);return a}
 async function legacy(){if(year>2005)throw Error('legacy fallback only 2000-2005');const csv=await getText(`https://raw.githubusercontent.com/fantasydatapros/data/master/yearly/${year}.csv`),lines=csv.trim().split(/\r?\n/),head=csvLine(lines.shift()),ix=Object.fromEntries(head.map((x,i)=>[x,i])),rows=[];for(const line of lines){const c=csvLine(line),p=pos(c[ix.Pos]);if(!['QB','RB','WR','TE'].includes(p))continue;const fp=Number(c[ix.FantasyPoints]);if(!c[ix.Player]||!Number.isFinite(fp))continue;rows.push({name:c[ix.Player],team:c[ix.Tm]||'FA',pos:p,fp})}rows.sort((a,b)=>b.fp-a.fp);const caps={QB:36,RB:75,WR:95,TE:45},cnt={};let depth=rows.filter(p=>(cnt[p.pos]=(cnt[p.pos]||0)+1)<=caps[p.pos]).map((p,i)=>({name:p.name,team:p.team,pos:p.pos,adp:31+i*.92,legacyProxy:true}));
  // Preserve authentic archived market leaders when a Wayback snapshot is available; depth remains a documented proxy.
  try{const u=`https://web.archive.org/web/20050806005351id_/http://football.myfantasyleague.com:80/${year}/draft_analysis`,h=await getText(u),top=[];for(const m of h.matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/gi)){const c=[...m[1].matchAll(/<td[^>]*>([\s\S]*?)<\/td>/gi)].map(x=>clean(x[1]));const adp=c.map(x=>Number(x)).find(x=>Number.isFinite(x)&&x>0&&x<400),name=c.find(x=>/[A-Za-z]{2,}\s+[A-Za-z]/.test(x)&&!/(Displaying|Average|Player|Draft)/i.test(x));if(name&&adp)top.push({name,adp})}if(top.length){const by=new Map(depth.map(x=>[x.name.toLowerCase(),x]));top.slice(0,30).forEach((x,i)=>{const p=by.get(x.name.toLowerCase());if(p)p.adp=Number(x.adp)||i+1});depth.sort((a,b)=>a.adp-b.adp)}}catch(e){}
  return finalize(depth,`Legacy ${year} player pool (archived market leaders where available; deep-round proxy)`)}
 let data,errors=[],minimum=Math.max(120,teams*15);for(const fn of [mfl,ffc,fftoday,legacy]){try{const d=await fn();if(d.players.length>=minimum){data=d;break}errors.push(`${d.source}: only ${d.players.length}`)}catch(e){errors.push(String(e.message||e))}}
 if(!data)return res.status(502).json({error:'Historical season data unavailable',year,detail:errors.join(' | ')});
 res.setHeader('Cache-Control','public, s-maxage=86400, stale-while-revalidate=604800');res.setHeader('Access-Control-Allow-Origin','*');return res.status(200).json({...data,teams,scoring});
};